# vi settings
setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# history limit
set -g history-limit 100000
setw -g alternate-screen on

# use mouse
set -g mouse on


# prefix key change
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "conf reloaded"

# split window
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# select pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind b set-option status

# resize pane
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# window number
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# true color
set -g default-terminal "xterm-256color"
set -as terminal-features ",xterm-256color:RGB"
set -ag terminal-overrides ",xterm-256color:RGB"

set -sg escape-time 0

# layout presets
#   active pane : other = 6:4 (only in 2 pane)
bind M-2 run-shell "idx=\$(tmux display-message -p '#{pane_index}'); tmux select-layout main-vertical; [ \"\$idx\" = \"1\" ] && tmux resize-pane -t 1 -x '60%' || tmux resize-pane -t 1 -x '40%'"
#   pane 1,2 : pane 3 = 6:4 (only in 3 pane)
bind M-3 run-shell "~/.config/tmux/scripts/three-pane-layout.sh"

# status bar
set -g status-bg "#d5d6db"
set -g status-fg "#343b58"
set -g status-right "[#h]"
set -g status on
set -g pane-border-style fg="#585b70"
set -g pane-active-border-style fg="#89b4fa"

# image setup
set -gq allow-passthrough on
set -g visual-activity off
set -g focus-events on

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'sainnhe/tmux-fzf'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
